name: CI

on:

  push:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          ndk-version: '21.0.6113669'
          cmake-version: '3.10.2.4988404'

      - name: Install apksigner and zipalign
        run: |
          echo "y" | sdkmanager --install "build-tools;30.0.1"
